#!/bin/sh 

INSTALLER=yum

sudo $INSTALLER install git
sudo $INSTALLER install vim
sudo $INSTALLER install curl
sudo $INSTALLER install gcc

git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
git clone https://github.com/eugeneching/consolas-powerline-vim.git ~/.fonts

cp ./gitconfig ~/.gitconfig 
cp ./vimrc ~/.vimrc 

# 想要使用tmux, 必须自己事先安装

