set nocompatible " be iMproved
filetype off " required!
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'AutoComplPop'
Bundle 'The-NERD-tree'
Bundle 'molokai'
Bundle 'bling/vim-bufferline'
Bundle 'tpope/vim-fugitive'
Bundle 'kien/ctrlp.vim'
Bundle 'scrooloose/syntastic'

set encoding=utf-8
set tabstop=2
set softtabstop=2
set shiftwidth=2
set autoindent
set cindent
set expandtab
set nu
"set mouse=a
set hlsearch
set backspace=2
set t_Co=256
colorscheme molokai
syntax on

map <F3> :NERDTreeMirror<CR>
map <F3> :NERDTreeToggle<CR>

